# Generated by Django 2.2.9 on 2022-04-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220426_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'публикацию', 'verbose_name_plural': 'публикации'},
        ),
    ]
