# Generated by Django 2.2.16 on 2022-08-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
